function data()
return {
	en = {
		["mod_name"] = "ICE T (Class 411/415) and TD (Class 605) of Deutsche Bahn",
		["mod_desc"] = "The series 411 and 415 are trains of the Deutsche Bahn, which are equipped as ICE with tilting technology. These trains with tilting technology were procured as feeders or supplements for the DB Intercity Express network. The ÖBB had in the meantime taken over 3 units, but in the meantime handed them back to the DB.\n\nThe diesel variant is run as the 605 series, the only ICE with diesel drive. The majority of the trains were in service to Denmark until 2017. All trains had been withdrawn by 2017.",

        ["Fake"] = "Activate fake versions?",
        ["option_fake_ice_t_desc"] = "You can choose if fake versions of the ICE T and TD should be hidden (default) or shown in depot.",

        ["ICE_TD_menu"] = "ICE TD (Class 605)",
        ["ICE_T_menu"] = "ICE T (Class 411/Class 415)",
		["ICE_TD_BR605_name"] = "ICE TD (Class 605) DB",
		["ICE_TD_BR605_DSB_name"] = "ICE TD (Class 605) DSB logo",
        ["ICE_TD_BR605_DSB_dsb_name"] = "ICE TD (Class 605) DSB colors",
		["ICE_TD_BR605_DSB_ICE_name"] = "ICE TD (Class 605) DSB ICE logo",
        ["ICE_T_BR411_bistro_name"] = "ICE T 7-pcs (Class 411) DB BordBistro",
        ["ICE_T_BR411_name"] = "ICE T 7-tlg. (Class 411) DB BordRestaurant",
        ["ICE_T_BR411_2ndseries_name"] = "ICE T 7-pcs (Class 411) DB (2nd series)",
        ["ICE_T_BR411_ICE_name"] = "ICE T 7-pcs (Class 411) DB ICE logo",
        ["ICE_T_BR411_oebb_name"] = "ICE T 7-pcs (Class 4011) ÖBB",
        ["ICE_T_BR411_db_oebb_name"] = "ICE T 7-pcs (Class 411) DB with ÖBB",
        ["ICE_T_BR411_klima_name"] = "ICE T 7-pcs (Class 411) DB Climate saver",
        ["ICE_T_BR411_2ndseries_klima_name"] = "ICE T 7-pcs (Class 411) DB Climate saver (2nd series)",
        ["ICE_T_BR415_name"] = "ICE T 5-pcs (Class 415) DB",
        ["ICE_T_BR415_ICE_name"] = "ICE T 5-pcs (Class 415) DB ICE-Logo",
        ["ICE_T_BR415_klima_name"] = "ICE T 5-pcs (Class 415) DB Climate saver",       

		["ICE_T_BR411_desc"] = "The ICE T was developed at the same time as the ICE 3, but not for high-speed traffic, but for feeder services on upgraded lines. For this purpose, it is equipped with tilting technology to be faster on these routes. The class 411 is the seven-car version of the train, which was equipped with a fully-fledged on-board restaurant from 2009.",
        ["ICE_T_BR411_2ndseries_desc"] = "The ICE T was developed at the same time as the ICE 3, but not for high-speed traffic, but for feeder services on upgraded lines. For this purpose, it is equipped with tilting technology to be faster on these routes. The class 411 is the seven-car version of the train. From 2004, the second series was delivered, which meant that enough trains were available to take over further routes.",
        ["ICE_T_BR411_bistro_desc"] = "The ICE T was developed at the same time as the ICE 3, but not for high-speed traffic, but for feeder services on upgraded lines. For this purpose, it is equipped with tilting technology to be faster on these routes. The class 411 is the seven-car version of the train, which was initially equipped with an on-board bistro.",
        ["ICE_T_BR411_db_oebb_desc"] = "After ÖBB sold the ICE T back to Deutsche Bahn in the year, they are still in use on the route to and from Vienna. They are therefore marked with a \"in cooperation with ÖBB\".",
        ["ICE_T_BR411_ICE_desc"] = "After the ICE T was a train without an ICE logo, some vehicles were fitted with one during the redesign in 2013.",
        ["ICE_T_BR411_klima_desc"] = "Since 2019, all ICE trains have gradually been fitted with green stripes at the ends to signal the use of green electricity on the ICE. In addition, the design have been brought up to date.",
        ["ICE_T_BR411_2ndseries_klima_desc"] = "Since 2019, all ICE trains have gradually been fitted with green stripes at the ends to signal the use of green electricity on the ICE. In addition, the design have been brought up to date. Train of second series.",
        ["ICE_T_BR411_oebb_desc"] = "In 2006, ÖBB bought a total of 3 multiple units for the Frankfurt-Vienna route. These trains bore the ÖBB logo and the series number 4011. In 2020, ÖBB sold the trains back to DB.",
        ["ICE_T_BR415_desc"] = "The ICE T was developed at the same time as the ICE 3, but not for high-speed traffic, but for feeder services on upgraded lines. For this purpose, it is equipped with tilting technology to be faster on these routes. The class 415 is the five-car version of the train, which is equipped with an on-board bistro in the multi-purpose car. The trains are mainly used as reinforcement units with a class 411.",
        ["ICE_T_BR415_ICE_desc"] = "After the ICE T was a train without an ICE logo, some vehicles were fitted with one during the redesign in 2013. The class 415 is mainly used as reinforcement units with a class 411.",
        ["ICE_T_BR415_klima_desc"] = "Since 2019, all ICE trains have gradually been fitted with green stripes at the ends to signal the use of green electricity on the ICE. In addition, the addresses have been brought up to date. The class 415 is mainly used as reinforcement units with a class 411.",
        
        ["ICE_TD_BR605_desc"] = "The ICE TD is DB's only diesel-powered ICE. It was used in regular service from 2001, but was never particularly appreciated or economical. Operation ended again in 2017 due to many technical problems.",
		["ICE_TD_BR605_DSB_desc"] = "In 2007, a lease of what later became a total of 10 trains to the Danish State Railways (DSB) began, with which services between Hamburg and Copenhagen, and later also from Berlin, were started. For this purpose, the trains were technically rebuilt and provided with a DSB logo.",
        ["ICE_TD_BR605_DSB_dsb_desc"] = "After a long request from DSB, an ICE TD was covered with foil in DSB's corporate colours in 2014.",
        ["ICE_TD_BR605_DSB_ICE_desc"] = "During a general overhaul, the trains were also painted with the ICE logo from 2013, which they previously lacked, analogous to the ICE T. The lease was extended until 2021.",        

        ["ICE_TD_Bpmf605.0_name"] = "2nd class end car Bpmf 605.0",
        ["ICE_TD_Bpmb605.1_name"] = "2nd class car Bpmb 605.1",
        ["ICE_TD_BRpm605.2_name"] = "Bordbistro/2nd class car BRpm 605.2",
        ["ICE_TD_Apmf605.5_name"] = "1st class end car Apmf 605.5",

        ["ICE_T_Apmzf411.0_name"] = "1st class end car Apmzf 411.0",
        ["ICE_T_ABpmz411.1_name"] = "1st/2nd class car ABpmz 411.1",
        ["ICE_T_WRmz411.2_bistro_name"] = "BordBistro WRmz 411.2",
        ["ICE_T_WRmz411.2_name"] = "BordRestaurant WRmz 411.2",
        ["ICE_T_Bpmz411.8_name"] = "2nd class car Bpmz 411.8",
        ["ICE_T_Bpmz411.7_name"] = "2nd class car Bpmz 411.7",
        ["ICE_T_Bpmbz411.6_name"] = "2nd class service car Bpmbz 411.6",
        ["ICE_T_Bpmzf411.5_name"] = "2nd class end car Bpmzf 411.5",

        ["ICE_T_Apmzf415.0_name"] = "1st class end car Apmzf 415.0",
        ["ICE_T_BRpmz415.1_name"] = "BordRestaurant/2nd class car BRpmz 415.1",
        ["ICE_T_Bpmz415.7_name"] = "2nd class car Bpmz 415.7",
        ["ICE_T_Bpmbz415.6_name"] = "2nd class service car Bpmbz 415.6",
        ["ICE_T_Bpmzf415.5_name"] = "2nd class end car Bpmzf 411.5",

        ["ICE_TD_fake_menu"] = "ICE TD (Class 605) FAKE",
        ["ICE_T_fake_menu"] = "ICE T (Class 411/Class 415) FAKE",
	},
	de = {
		["mod_name"] = "ICE T (BR 411/415) und TD (BR 605) der Deutschen Bahn",
		["mod_desc"] = "Die Baureihen 411 und 415 sind Züge der Deutschen Bahn, die als ICE mit Neigetechnik ausgestattet sind. Diese Züge mit Neigetechnik wurden als Zubringer oder Ergänzung für das Intercity-Express-Netz der DB beschafft. Die ÖBB hatte zwischenzeitlich 3 Einheiten übernommen, inzwischen aber wieder an die DB abgegeben.\n\nAls Baureihe 605 wird die Dieselvariante geführt, der einzige ICE mit Dieselantrieb. Der Großteil der Züge kam bis 2017 im Verkehr nach Dänemark zum Einsatz. Bis 2017 wurden alle Züge abgestellt.",

        ["Fake"] = "Fake-Versionen aktivieren?",
        ["option_fake_ice_t_desc"] = "Schaltet die Fake-Versionen des ICE T und TD ab (Standard) oder an.",

        ["ICE_TD_menu"] = "ICE TD (BR 605)",
        ["ICE_T_menu"] = "ICE T (BR 411/BR 415)",
		["ICE_TD_BR605_name"] = "ICE TD (BR 605) DB",
		["ICE_TD_BR605_DSB_name"] = "ICE TD (BR 605) DSB Logo",
        ["ICE_TD_BR605_DSB_dsb_name"] = "ICE TD (BR 605) DSB Farben",
		["ICE_TD_BR605_DSB_ICE_name"] = "ICE TD (BR 605) DSB ICE-Logo",
        ["ICE_T_BR411_bistro_name"] = "ICE T 7-tlg. (BR 411) DB BordBistro",
        ["ICE_T_BR411_name"] = "ICE T 7-tlg. (BR 411) DB BordRestaurant",
        ["ICE_T_BR411_2ndseries_name"] = "ICE T 7-tlg. (BR 411) DB (2. Serie)",
        ["ICE_T_BR411_ICE_name"] = "ICE T 7-tlg. (BR 411) DB ICE-Logo",
        ["ICE_T_BR411_oebb_name"] = "ICE T 7-tlg. (BR 4011) ÖBB",
        ["ICE_T_BR411_db_oebb_name"] = "ICE T 7-tlg. (BR 411) DB mit ÖBB",
        ["ICE_T_BR411_klima_name"] = "ICE T 7-tlg. (BR 411) DB Klimaschützer",
        ["ICE_T_BR411_2ndseries_klima_name"] = "ICE T 7-tlg. (BR 411) DB Klimaschützer (2. Serie)",
        ["ICE_T_BR415_name"] = "ICE T 5-tlg. (BR 415) DB",
        ["ICE_T_BR415_ICE_name"] = "ICE T 5-tlg. (BR 415) DB ICE-Logo",
        ["ICE_T_BR415_klima_name"] = "ICE T 5-tlg. (BR 415) DB Klimaschützer",       

		["ICE_T_BR411_desc"] = "Der ICE T wurde zeitgleich mit dem ICE 3 entwickelt, aber nicht für den Hochgeschwindigkeitsverkehr, sondern für Zubringerleistungen auf Ausbaustrecken. Dafür ist er mit Neigetechnik ausgerüstet, um auf diesen Strecken schneller zu sein. Die Baureihe 411 ist die siebenteilige Version des Zuges, der ab 2009 mit einem vollwertigen Bordrestaurant ausgestattet war.",
        ["ICE_T_BR411_2ndseries_desc"] = "Der ICE T wurde zeitgleich mit dem ICE 3 entwickelt, aber nicht für den Hochgeschwindigkeitsverkehr, sondern für Zubringerleistungen auf Ausbaustrecken. Dafür ist er mit Neigetechnik ausgerüstet, um auf diesen Strecken schneller zu sein. Die Baureihe 411 ist die siebenteilige Version des Zuges. Ab 2004 wurde die zweite Bauserie geliefert, womit genug Züge zur Verfügung standen um weitere Strecken zu übernehmen.",
        ["ICE_T_BR411_bistro_desc"] = "Der ICE T wurde zeitgleich mit dem ICE 3 entwickelt, aber nicht für den Hochgeschwindigkeitsverkehr, sondern für Zubringerleistungen auf Ausbaustrecken. Dafür ist er mit Neigetechnik ausgerüstet, um auf diesen Strecken schneller zu sein. Die Baureihe 411 ist die siebenteilige Version des Zuges, der anfangs mit einem Bordbistro ausgestattet war.",
        ["ICE_T_BR411_db_oebb_desc"] = "Nachdem die ÖBB die ICE T im Jahr wieder an die Deutsche Bahn zurückverkauft hat, sind diese weiterhin im Einsatz auf der Strecke von und nach Wien. Sie sind daher mit einem \"in Kooperation mit ÖBB\" gekennzeichnet.",
        ["ICE_T_BR411_ICE_desc"] = "Nach dem der ICE T ein Zug ohne ICE Logo war, wurde beim Redesign im Jahr 2013 bei einiges Fahrzeugen ein solches angebracht.",
        ["ICE_T_BR411_klima_desc"] = "Seit dem Jahr 2019 werden alle ICE nach und nach mit grünem Streifen an den Enden beklebt, um den Einsatz von Ökostrom beim ICE zu signalisieren. Außerdem wurden die Anschriften auf den aktuellen Stand gebracht.",
        ["ICE_T_BR411_2ndseries_klima_desc"] = "Seit dem Jahr 2019 werden alle ICE nach und nach mit grünem Streifen an den Enden beklebt, um den Einsatz von Ökostrom beim ICE zu signalisieren. Außerdem wurden die Anschriften auf den aktuellen Stand gebracht. Zug der 2. Serie.",
        ["ICE_T_BR411_oebb_desc"] = "Im Jahr 2006 kaufte die ÖBB insgesamt 3 Triebzüge für die Strecke Frankfurt-Wien. Diese Züge trugen das ÖBB-Logo sowie die Baureihennummer 4011. Im Jahr 2020 verkaufte die ÖBB die Züge zurück an die DB.",
        ["ICE_T_BR415_desc"] = "Der ICE T wurde zeitgleich mit dem ICE 3 entwickelt, aber nicht für den Hochgeschwindigkeitsverkehr, sondern für Zubringerleistungen auf Ausbaustrecken. Dafür ist er mit Neigetechnik ausgerüstet, um auf diesen Strecken schneller zu sein. Die Baureihe 415 ist die fünfteilige Version des Zuges, der mit einem Bordbistro im Mehrzweckwagen ausgestattet ist. Die Züge kommen vor allem als Verstärkereinheiten mit einer BR 411 zum Einsatz.",
        ["ICE_T_BR415_ICE_desc"] = "Nach dem der ICE T ein Zug ohne ICE Logo war, wurde beim Redesign im Jahr 2013 bei einiges Fahrzeugen ein solches angebracht. Die BR 415 kommen vor allem als Verstärkereinheiten mit einer BR 411 zum Einsatz.",
        ["ICE_T_BR415_klima_desc"] = "Seit dem Jahr 2019 werden alle ICE nach und nach mit grünem Streifen an den Enden beklebt, um den Einsatz von Ökostrom beim ICE zu signalisieren. Außerdem wurden die Anschriften auf den aktuellen Stand gebracht. Die BR 415 kommen vor allem als Verstärkereinheiten mit einer BR 411 zum Einsatz.",
        
        ["ICE_TD_BR605_desc"] = "Der ICE TD ist der einzige dieselbetriebene ICE der DB. Er wurde ab 2001 im Linienbetrieb eingesetzt, war allerdings nie besonders geschätzt oder wirtschaftlich. Der Betrieb endete bereits im Jahr 2017 wieder aufgrund vieler technischer Probleme.",
		["ICE_TD_BR605_DSB_desc"] = "Im Jahr 2007 begann eine Vermietung von später insgesamt 10 Zügen an die Dänischen Staatsbahnen (DSB) mit der der Verkehr zwischen Hamburg und Kopenhagen, später auch von Berlin aus aufgenommen wurde. Dazu wurden die Züge technisch umgebaut und mit einem Logo der DSB versehen.",
        ["ICE_TD_BR605_DSB_dsb_desc"] = "Nach langem Bitten seitens der DSB wurde im Jahr 2014 ein ICE TD mit Folie in den Hausfarben der DSB beklebt.",
        ["ICE_TD_BR605_DSB_ICE_desc"] = "Bei einer allgemein anstehenden Revision wurden die Züge ab 2013 auch mit ICE Logo lackiert, was ihnen vorher fehlte analog zum ICE T. Die Vermietung wurde bis ins Jahr 2021 verlängert.",        

        ["ICE_TD_Bpmf605.0_name"] = "2. Kl.-Endwagen Bpmf 605.0",
        ["ICE_TD_Bpmb605.1_name"] = "2. Kl.-Wagen Bpmb 605.1",
        ["ICE_TD_BRpm605.2_name"] = "Bordbistro/2. Kl.-Wagen BRpm 605.2",
        ["ICE_TD_Apmf605.5_name"] = "1. Kl.-Endwagen Apmf 605.5",

        ["ICE_T_Apmzf411.0_name"] = "1. Kl.-Endwagen Apmzf 411.0",
        ["ICE_T_ABpmz411.1_name"] = "1./2. Kl.-Wagen ABpmz 411.1",
        ["ICE_T_WRmz411.2_bistro_name"] = "BordBistro WRmz 411.2",
        ["ICE_T_WRmz411.2_name"] = "BordRestaurant WRmz 411.2",
        ["ICE_T_Bpmz411.8_name"] = "2. Kl.-Wagen Bpmz 411.8",
        ["ICE_T_Bpmz411.7_name"] = "2. Kl.-Wagen Bpmz 411.7",
        ["ICE_T_Bpmbz411.6_name"] = "2. Kl.-Servicewagen Bpmbz 411.6",
        ["ICE_T_Bpmzf411.5_name"] = "2. Kl.-Endwagen Bpmzf 411.5",

        ["ICE_T_Apmzf415.0_name"] = "1. Kl.-Endwagen Apmzf 415.0",
        ["ICE_T_BRpmz415.1_name"] = "BordRestaurant/2. Kl.-Wagen BRpmz 415.1",
        ["ICE_T_Bpmz415.7_name"] = "2. Kl.-Wagen Bpmz 415.7",
        ["ICE_T_Bpmbz415.6_name"] = "2. Kl.-Servicewagen Bpmbz 415.6",
        ["ICE_T_Bpmzf415.5_name"] = "2. Kl.-Endwagen Bpmzf 411.5",

        ["ICE_TD_fake_menu"] = "ICE TD (BR 605) FAKE",
        ["ICE_T_fake_menu"] = "ICE T (BR 411/BR 415) FAKE",
	},
}
end
